//! TypeScript discriminated-union emitters for entity lifecycle states.

use crate::{EmitError, Emitter, Scope, View};
use rdra_ish_core::{
    collect_entity_state_variants, EntityStateVariant, EntityStateVariants, SemanticModel,
    StateFieldValue, DEFAULT_PATTERN_CAP,
};

pub struct TypeScriptStateUnionEmitter {
    pub cap: usize,
}

impl Default for TypeScriptStateUnionEmitter {
    fn default() -> Self {
        Self {
            cap: DEFAULT_PATTERN_CAP,
        }
    }
}

impl Emitter for TypeScriptStateUnionEmitter {
    fn emit(&self, model: &SemanticModel, view: &View) -> Result<String, EmitError> {
        let buc_filter = match &view.scope {
            Scope::Bucs(ids) => ids.clone(),
            Scope::Whole | Scope::UseCases(_) => vec![],
        };
        let collections = collect_entity_state_variants(model, &buc_filter, self.cap);
        Ok(emit_typescript_state_unions(&collections))
    }
}

pub fn emit_typescript_state_unions(collections: &[EntityStateVariants]) -> String {
    let mut out = String::from("// Generated by rdra-ish. Do not edit manually.\n\n");
    for collection in collections {
        if collection.variants.is_empty() {
            continue;
        }
        out.push_str(&emit_entity_union(collection));
        out.push('\n');
    }
    out
}

fn emit_entity_union(collection: &EntityStateVariants) -> String {
    let type_name = to_pascal_case(&collection.entity_id);
    let mut out = format!(
        "/** Reachable state variants for {}. */\n",
        collection.entity_id
    );
    out.push_str(&format!("export type {type_name} =\n"));

    for (index, variant) in collection.variants.iter().enumerate() {
        let prefix = if index == 0 { "  " } else { "  | " };
        out.push_str(prefix);
        out.push_str(&emit_variant_object(collection, variant));
        out.push('\n');
    }
    out.push_str(";\n");
    out
}

fn emit_variant_object(collection: &EntityStateVariants, variant: &EntityStateVariant) -> String {
    let mut lines = vec![format!(
        "{}: {};",
        collection.discriminator_column,
        ts_string_literal(&variant.discriminator)
    )];

    for (column, value) in &variant.fields {
        lines.push(format!("{column}: {};", ts_type_for_field(value)));
    }

    if lines.len() == 1 {
        return format!("{{ {} }}", lines[0]);
    }

    let body = lines
        .into_iter()
        .map(|line| format!("    {line}"))
        .collect::<Vec<_>>()
        .join("\n");
    format!("{{\n{body}\n  }}")
}

fn ts_type_for_field(value: &StateFieldValue) -> String {
    match value {
        StateFieldValue::Enum(variant) => ts_string_literal(variant),
        StateFieldValue::Bool(_) => "boolean".to_string(),
        StateFieldValue::Null => "null".to_string(),
        StateFieldValue::Present { pg_type } => match pg_type.as_deref() {
            Some("timestamptz" | "timestamp" | "date") => "Date".to_string(),
            Some("uuid") => "string".to_string(),
            Some("json" | "jsonb") => "Record<string, unknown>".to_string(),
            Some("money" | "decimal") => "number".to_string(),
            Some(_) => "string".to_string(),
            None => "unknown".to_string(),
        },
    }
}

fn ts_string_literal(value: &str) -> String {
    format!("\"{}\"", escape_ts_string(value))
}

fn escape_ts_string(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

fn to_pascal_case(id: &str) -> String {
    let mut out = String::new();
    let mut upper = true;
    for ch in id.chars() {
        if ch == '_' || ch == '-' {
            upper = true;
            continue;
        }
        if upper {
            out.extend(ch.to_uppercase());
            upper = false;
        } else {
            out.push(ch);
        }
    }
    if out.is_empty() {
        "Entity".to_string()
    } else {
        out
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use rdra_ish_core::analysis::build_model;
    use rdra_ish_syntax::parse;

    fn model_from(src: &str) -> SemanticModel {
        let (ast, parse_errors) = parse(src);
        assert!(parse_errors.is_empty(), "parse errors: {parse_errors:?}");
        let (model, diags) = build_model(&ast);
        assert!(diags.is_empty(), "unexpected diagnostics: {diags:?}");
        model
    }

    const ORDER_SRC: &str = r#"
entity Order "注文" {
  id:           Int @pk
  status:       Enum(pending, paid, shipped, delivered, cancelled) @default(pending)
  delivered_at: DateTime @null
}
usecase PlaceOrder  "注文確定"
usecase CapturePay  "決済確定"
usecase ShipOrder   "発送"
usecase DeliverOrder "配達確認"
usecase CancelOrder "注文キャンセル"
event EvCapture  "決済確定"
event EvShip     "発送開始"
event EvDeliver  "配達確認"
event EvCancel   "注文キャンセル"
creates(PlaceOrder, Order)
updates(CapturePay,   Order)
updates(ShipOrder,    Order)
updates(DeliverOrder, Order)
updates(CancelOrder,  Order)
raises(CapturePay,   EvCapture)
raises(ShipOrder,    EvShip)
raises(DeliverOrder, EvDeliver)
raises(CancelOrder,  EvCancel)
state Pending   "注文受付"
state Paid      "決済完了"
state Shipped   "発送済"
state Delivered "配達完了"
state Cancelled "キャンセル"
transitions(Order.status, EvCapture, pending -> paid)
transitions(Order.status, EvShip, paid -> shipped)
transitions(Order.status, EvDeliver, shipped -> delivered)
transitions(Order.status, EvCancel, pending -> cancelled)
sets(usecase::DeliverOrder, Order, delivered_at == present)
"#;

    #[test]
    fn typescript_state_union_snapshot() {
        let model = model_from(ORDER_SRC);
        let collections = collect_entity_state_variants(&model, &[], DEFAULT_PATTERN_CAP);
        insta::assert_snapshot!(emit_typescript_state_unions(&collections));
    }

    #[test]
    fn emitter_matches_helper() {
        let model = model_from(ORDER_SRC);
        let view = View::whole();
        let from_emitter = TypeScriptStateUnionEmitter::default()
            .emit(&model, &view)
            .unwrap();
        let collections = collect_entity_state_variants(&model, &[], DEFAULT_PATTERN_CAP);
        assert_eq!(from_emitter, emit_typescript_state_unions(&collections));
    }
}
